# 1. Files excluded from Jekyll builds
exclude:
- README.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- screenshot.png
- LICENSE
- CNAME
- Gemfile
- Gemfile.lock
- alembic-jekyll-theme.gemspec
- .jekyll-cache

# 2. Installed Gems
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji

remote_theme: daviddarnes/alembic@main


# 3. Gem settings
paginate: 1 # jekyll-paginate > items per page
paginate_path: blog/page:num # jekyll-paginate > blog page
twitter:
  username: resdatall # jekyll-seo-tag > Owners twitter username
author: fdo # jekyll-seo-tag > default author
social: # jekyll-seo-tag > social overrides
  name: FAIR Digital Objects # jekyll-seo-tag > real name
  links:  # jekyll-seo-tag > social aliases (sameAs)
    - https://github.com/fairdo

# 4. Jekyll settings
sass:
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: Europe/Amsterdam # Timezone for blog posts and alike

# 5. Collections
collections:
  posts:
    title: News # Needed for Siteleaf
    output: true
    description: "news and events" # The post list page content
    feature_text: |
      News and events related to FAIR Digital Objects 
    feature_image: "/assets/splash.jpeg"

# 6. Jekyll collections settings
defaults:
  -
    scope:
      path: ""
    values:
      image: "/assets/default-social-image.png" # Default image for sharing
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages

# 7. Site settings
encoding: utf-8 # Make sure the encoding is right
lang: en-GB # Set the site language
title: "FAIR Digital Objects" # Site name or title, also used in jekyll-seo-tag
logo: "/assets/logos/fdo-content-transp.png" # Site logo, also used in jekyll-seo-tag
description: "FAIR Digital Objects"
url: "https://fairdo.org" # Site url, also used in jekyll-seo-tag
baseurl: ""
repo: "https://github.com/fairdo/fairdo.github.io"
email: "info@fairdo.org"
# google_analytics: ''
# google_analytics_anonymize_ip: ''
# service_worker: false # Will turn off the service worker if set to false
css_inline: true # Will insert all styles into a single <style> block in the <head> element and remove the style <link> reference

# 8. Site favicons & manifest icons
favicons: # Favicons are also used in the manifest file. Syntax is 'size: path'
  16: '/assets/favicons/favicon-16x16.png'
  32: '/assets/favicons/favicon-32x32.png'

# 9. Site navigation
navigation_header:
- title: Home
  url: /
- title: Working Groups
  url: /wg/
- title: Publications
  url: /publications/
- title: News and Events 
  url: /news/
- title: About
  url: /about/
- title: Search
  url: /search/

navigation_footer:
  - title: source code for this site
    url: https://github.com/fairdo/fairdo.github.io

social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  GitHub: https://github.com/fairdo/fairdo.github.io
  link: https://fairdo.org

sharing_links: # Appear at the bottom of single blog posts, add as desired. The value can be 'true' or the desired button colour
  Twitter: "#0d94e7"
  Email: true
