
# Site settings
title: FAIR Digital Objects
description: Turning Data to Knowledge
image: /assets/img/twitter_profile.png
twitter: https://twitter.com/resdatall/
github_info:
  organization: fairdo
  repository: fairdo.github.io
  default_branch: master

reomte_theme: uswds-jekyll
url: "https://fairdo.org" # the base hostname & protocol for your site
plugins:
  - jekyll-redirect-from
  - jekyll-sitemap

exclude:
  - CONTRIBUTING.md
  - circle.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - vendor
  - webpack.config.js

keep_files:

scripts:
  - /assets/uswds/js/uswds.min.js

styles:
  - href: /assets/css/main.css
    media: screen, print

sass:
  load_paths:
    - _sass
    - node_modules
  style: compressed

defaults:
  - scope:
      path: "assets/uswds"
    values:
      skip_index: true
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "docs"
  - scope:
      path: "_pages/wg"
    values:
      pagination: true

collections:
  pages:
    output: true
    permalink: /:path/

kramdown:
  parse_block_html: true

jekyll_pages_api_search:
  skip_index: false
  index_fields:
    title:
      boost: 10
    tags:
      boost: 10
    url:
      boost: 5
    body:
  results_page_title: Search results
